;; dt means delete-to
(defun dt (tstr)
  "delete to an archor in a line"
  (interactive "sInput boundary charcters: ")
  (setq ll (length tstr)) 
  (setq pt0  (point))
  (setq pt1  (point))
  (setq pt2 (line-end-position))
  (setq str (buffer-substring pt1 pt2))
  (while (< pt1 pt2)
     (if (string= (buffer-substring pt1 (+ pt1 ll)) tstr)
	 (let () 
	   (setq pt3 (+ pt1 ll))
	   ;;(setq pt3 (+ pt3 1))
	   (delete-region pt0 pt3)
	   (setq pt1 pt2)
	   )
       (setq pt1 (+ pt1 1))
       )
))

;; choose this name because df are close in keyboard
(defun df (tstr)
  "delete before an anchor in a line"
  (interactive "sInput boundary charcters: ")
  (setq ll (length tstr)) 
  (setq pt0  (point))
  (setq pt1  (point))
  (setq pt2 (line-end-position))
  (setq str (buffer-substring pt1 pt2))
  (while (< pt1 pt2)
     (if (string= (buffer-substring pt1 (+ pt1 ll)) tstr)
	 (let () 
	   (setq pt3 pt1)
	   (delete-region pt0 pt3)
	   (setq pt1 pt2)
	   )
       (setq pt1 (+ pt1 1))
       )
))
